### ISSUE TITLE
Tests broken by 'is_3' removal

### ISSUE THREAD

**Issue by mgorny** [tikitu/jsmin#35]
The tests are broken in the 3.0.0 release:

```
$ PYTHONPATH=. python jsmin/test.py 
.....................................................................EEEEEEE
======================================================================
ERROR: test_character_class (__main__.RegexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/jsmin/jsmin/test.py", line 618, in test_character_class
    self.assert_regex('/a[0-9]b/g', '/a[0-9]b/')
  File "/tmp/jsmin/jsmin/test.py", line 611, in assert_regex
    recognised = self.regex_recognise(js_input)
  File "/tmp/jsmin/jsmin/test.py", line 595, in regex_recognise
    if not jsmin.is_3:
AttributeError: module 'jsmin' has no attribute 'is_3'

======================================================================
ERROR: test_character_class_with_slash (__main__.RegexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/jsmin/jsmin/test.py", line 621, in test_character_class_with_slash
    self.assert_regex('/a[/]b/g', '/a[/]b/')
  File "/tmp/jsmin/jsmin/test.py", line 611, in assert_regex
    recognised = self.regex_recognise(js_input)
  File "/tmp/jsmin/jsmin/test.py", line 595, in regex_recognise
    if not jsmin.is_3:
AttributeError: module 'jsmin' has no attribute 'is_3'

======================================================================
ERROR: test_empty_character_class (__main__.RegexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/jsmin/jsmin/test.py", line 634, in test_empty_character_class
    self.assert_regex('/a[]/]b/g', '/a[]/]b/')
  File "/tmp/jsmin/jsmin/test.py", line 611, in assert_regex
    recognised = self.regex_recognise(js_input)
  File "/tmp/jsmin/jsmin/test.py", line 595, in regex_recognise
    if not jsmin.is_3:
AttributeError: module 'jsmin' has no attribute 'is_3'

======================================================================
ERROR: test_escaped_back_slash (__main__.RegexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/jsmin/jsmin/test.py", line 627, in test_escaped_back_slash
    self.assert_regex(r'/a\\/g', r'/a\\/')
  File "/tmp/jsmin/jsmin/test.py", line 611, in assert_regex
    recognised = self.regex_recognise(js_input)
  File "/tmp/jsmin/jsmin/test.py", line 595, in regex_recognise
    if not jsmin.is_3:
AttributeError: module 'jsmin' has no attribute 'is_3'

======================================================================
ERROR: test_escaped_forward_slash (__main__.RegexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/jsmin/jsmin/test.py", line 624, in test_escaped_forward_slash
    self.assert_regex(r'/a\/b/g', r'/a\/b/')
  File "/tmp/jsmin/jsmin/test.py", line 611, in assert_regex
    recognised = self.regex_recognise(js_input)
  File "/tmp/jsmin/jsmin/test.py", line 595, in regex_recognise
    if not jsmin.is_3:
AttributeError: module 'jsmin' has no attribute 'is_3'

======================================================================
ERROR: test_precedence_of_parens (__main__.RegexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/jsmin/jsmin/test.py", line 640, in test_precedence_of_parens
    self.assert_regex('/a([)])b/g', '/a([)])b/')
  File "/tmp/jsmin/jsmin/test.py", line 611, in assert_regex
    recognised = self.regex_recognise(js_input)
  File "/tmp/jsmin/jsmin/test.py", line 595, in regex_recognise
    if not jsmin.is_3:
AttributeError: module 'jsmin' has no attribute 'is_3'

======================================================================
ERROR: test_simple (__main__.RegexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/jsmin/jsmin/test.py", line 615, in test_simple
    self.assert_regex('/123/g', '/123/')
  File "/tmp/jsmin/jsmin/test.py", line 611, in assert_regex
    recognised = self.regex_recognise(js_input)
  File "/tmp/jsmin/jsmin/test.py", line 595, in regex_recognise
    if not jsmin.is_3:
AttributeError: module 'jsmin' has no attribute 'is_3'

----------------------------------------------------------------------
Ran 76 tests in 0.034s

FAILED (errors=7)
```

**Comment by jonringer** [comment]
can you do a patch release? seems weird to apply an a patch for a fix that was made 4 months ago

**Comment by tikitu** [comment]
I've made a patch release, sorry for the inconvenience.
